---
# tasks file for sysstat

- block:
    - name: install sysstat
      become: yes
      become_method: sudo
      apt:
        name: sysstat
        cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
        install_recommends: no
        state: latest
        update_cache: yes

    # For Ubuntu Xenial 16.04 and below
    - block:

      - name: copy sysstat default configuration
        template:
          src: default_sysstat.j2
          dest: /etc/default/sysstat
          backup: no
          mode: "0644"
        notify:
          - reload sysstat

      - name: ensure sysstat service running and enabled on boot
        service:
          name: "{{ sysstat_service_name }}"
          enabled: yes
          state: started

      when: ansible_distribution_version is version_compare('16.04', '<=')

    # For Ubuntu Bionic (18.04) and above
    - block:

      - name: copy sysstat default configuration
        template:
          src: default_sysstat.j2
          dest: /etc/default/sysstat
          backup: no
          mode: "0644"
        notify:
          - reload sysstat systemd

      - name: ensure sysstat service running and enabled on boot using systemd
        systemd:
          name: "{{ sysstat_service_name }}"
          state: started
          enabled: yes

      when: ansible_distribution_version is version_compare('16.04', '>')

  become: yes
  become_method: sudo
  tags:
    - sysstat
    - common
