---
# handlers file for sysstat

- name: reload sysstat
  become: yes
  become_method: sudo
  service:
    name: "{{ sysstat_service_name }}"
    state: reloaded
  tags:
    - sysstat

- name: reload sysstat systemd
  become: yes
  become_method: sudo
  systemd:
    name: "{{ sysstat_service_name }}"
    state: reloaded
  tags:
    - sysstat